### ISSUE TITLE
Expose parameteres with default values

### ISSUE THREAD

**Issue by leolobato** [fulldecent/FDSoundActivatedRecorder#17]
It might be useful to expose the parameters currently defined as private (e.g. `TOTAL_TIMEOUT_SECONDS`) for configuring the recorder according to the app's needs.

**Comment by fulldecent** [comment]
Agreed, yes.

Also, they need better Swifty names.

**Comment by fulldecent** [comment]
f9bfe73a79d4a333a6dbd0179b1dcf73b35a2cef adds proposed names and documentation for these parameters.

I'd like to have them right before making that API public.

**Comment by fulldecent** [comment]
What does everyone think about the existing names?

**Comment by leolobato** [comment]
Added a couple of notes at the commit. Looks good for me, except for the "sampleRate" parameter. 

I'm not sure if the "intervals" concept will be immediately clear to someone looking into tweaking the parameters, but I see it might be simpler than specifying ms for each of the parameters being tweaked.

**Comment by fulldecent** [comment]
The issue is that tweaking ms for each parameter is incompatible with our implementation.

**Comment by fulldecent** [comment]
Perhaps there is a way I can improve that documentation.

**Comment by fulldecent** [comment]
Thank you, just exposed this in a new release
