### ISSUE TITLE
Bug when listening && timeout

### ISSUE THREAD

**Issue by sabiland** [fulldecent/FDSoundActivatedRecorder#22]
Hi.

You have bug in your code. If status of recorder is still in "listening" and timeouts -> you never call abort on a delegate.

I've added this to fix this:

Line  ~220 (function abort()):

if status == .Recording **|| status == .Listening** {

**Comment by fulldecent** [comment]
Beautiful, thank you. Would you like to send as a PR?

**Comment by sabiland** [comment]
Sorry I do not know if this is bug anymore. I forgot to setup AVAudioSession, maybe my issues were because of that. I'll check today.

**Comment by sabiland** [comment]
I have checked my code and it really was my mistake. When I added AVAudioSession calls, everything works ok.

But just one info. If repeatedly calling FDSoundActivatedRecorder class (startListening), this only works if there is only one initialized instance of FDSoundActivatedRecorder object. If I initialized it every time I needed it - it worked only first time.

Any ideas or I am doing something wrong?

**Comment by sabiland** [comment]
I've checked everything again :) 

And I really think the line at ~200 should be:

if status == .Recording **|| status == .Listening {**

**Comment by fulldecent** [comment]
Thank you, fixed in 1de3642db92754068627ac1d0d65fb6ca5a4c785

**Comment by fulldecent** [comment]
Also made a new release so everyone can get this.
