### ISSUE TITLE
update to swift 4

### ISSUE THREAD

**Issue by aserdah** [fulldecent/FDSoundActivatedRecorder#23]
In the FDSoundActivatedRecorder.swift must change the following

@objc dynamic open var microphoneLevel: Double = 0.0 
 // line 135 in FDSoundActivatedRecorder.swift
 intervalTimer = Timer.scheduledTimer(timeInterval: intervalSeconds, target: self, selector: #selector(FDSoundActivatedRecorder.interval), userInfo: nil, repeats: true) 
// line 149 in FDSoundActivatedRecorder.swift
 let tracks = avAsset.tracks(withMediaType: AVMediaType.audio) 
// line 193 in FDSoundActivatedRecorder.swift
exportSession.outputFileType = AVFileType.m4a
 // line 204 in FDSoundActivatedRecorder.swift

**Comment by fulldecent** [comment]
Thank you! I am happy to provide you credit if you would like to send a pull request for this.

**Comment by MHX792** [comment]
Any updates on this?

**Comment by fulldecent** [comment]
Thank you, this is released at https://github.com/fulldecent/FDSoundActivatedRecorder/releases/tag/3.0.0
