### ISSUE TITLE
iPhone 5S woes

### ISSUE THREAD

**Issue by DreamTimerZ** [fulldecent/FDSoundActivatedRecorder#3]
Sync'd repo.  Built and loaded on to iPhone 5S using iOS 7.1.1.  Hit "Start" screen briefly flashes green and then immediately stops.

Verified app has microphone permissions.

Works fine in the simulator.

**Comment by dxcode** [comment]
Hi!

I'm using XCode Version 5.1.1 (5B1008) and I'm having the same problem on iPhone 5S - no sound.

Any luck finding the fix?

Much appreciated

**Comment by fulldecent** [comment]
Thanks for the details on this. Wife just got a 5S, will check on hers. However this is iOS 8.

**Comment by sri-omg** [comment]
I think I ran into this same problem. The audioRecorder never starts recording so the interval timer immediately times out. Adding this to init before creating the audioRecorder fixed it:
```
AVAudioSession *audioSession = [AVAudioSession sharedInstance];
[audioSession setCategory:AVAudioSessionCategoryPlayAndRecord error:nil];
[audioSession setActive:YES error:nil];
```
See this answer: http://stackoverflow.com/questions/18922053/avaudiorecorder-avaudioplayer-with-ios-7-not-working-properly

**Comment by fulldecent** [comment]
Excellent, thanks for the advice. Would you like to take credit for this with a PR?
