### ISSUE TITLE
SwiftUI ?

### ISSUE THREAD

**Issue by furiousteam** [fulldecent/FDSoundActivatedRecorder#30]
Any plan to update FDSoundActivatedRecorder to support SwiftUI ?

Thanks

**Comment by fulldecent** [comment]
There is no user interface for FDSoundActivatedRecorder. It is a model-only module.

But if somebody would like to rewrite the example project using SwiftUI then yes, we would appreciate that. And it could be a fun task.

**Comment by fulldecent** [comment]
Fixed in https://github.com/fulldecent/FDSoundActivatedRecorder/pull/36
