### ISSUE TITLE
Regular recording without trimming

### ISSUE THREAD

**Issue by HassanElDesouky** [fulldecent/FDSoundActivatedRecorder#31]
Hello, 
First of all, thanks for creating this amazing repo. It really helped me a lot! 

In my app use case, I want to provide a way for users to record regularly just like any other audio recorder without trimming the audio, starting when the user starts speaking, or anything. 

I tried to use the `startRecording` method however when I tap on my stop recording button, the `exportSession` inside the `stopAndSaveRecording` fails with an export status of `4` which means it failed. Therefore, it doesn't call the `soundActivatedRecorderDidFinishRecording` delegate method.

What I'm doing wrong, and how can I fix it?

Thanks!

**Comment by HassanElDesouky** [comment]
I solved it with the following:
I should call `startListening` before `startRecording`. Now I can record the audio as if it's a regular audio recorder!

I will try to update the README.md file because it wasn't clear!

**Comment by fulldecent** [comment]
Please confirm. Is your intention is that you will start recording manually and the recording will stop after the utterance?

**Comment by HassanElDesouky** [comment]
My institutions were to start recording manually and _stop_ recording manually. As if it's like any other recorder.
