### ISSUE TITLE
Continous Listening without Recording?

### ISSUE THREAD

**Issue by MHX792** [fulldecent/FDSoundActivatedRecorder#33]
I just want to get a notification when a user starts speaking, without the need of recording anything.

For this, I have set the timeoutSeconds to zero for indefinite listening.

```
       self.recorder.timeoutSeconds = 0
       self.recorder.startListening()
```

Is anything saved in the background by using `startListeening()`? If yes, this would prevent indefinite listening because of storage limitations.

**Comment by fulldecent** [comment]
This project is based on recording utterances.

This discusses monitoring on speaking levels and not recording. Closing as out of scope.

But you are welcome to add a new section under README / Usage if you would like to share this use case.
