### ISSUE TITLE
Use adaptive algorithm for determining if a user speaks

### ISSUE THREAD

**Issue by MHX792** [fulldecent/FDSoundActivatedRecorder#34]
This is somewhat related to issue https://github.com/fulldecent/FDSoundActivatedRecorder/issues/20.

Idea: 

1. save the last x microphone levels (e.g. for the last 30 seconds)
2. identify spikes: these would indicate that a user speaks
3. substract spikes from other saved levels in order identify valleys: these would indicate silence
4. use average of valleys as the threshold value for speaking
5. if the current microphone level is greater than the moving average, user is probably speaking

The advantage of such an algorithm is obvious: even if the surrounding circumstances change (e.g. the user leaves a building and is exposed to traffic noise), the recognition accuracy would still be high.

**Comment by fulldecent** [comment]
This project does real-time recording. But this issue proposes an approach to analyzing pre-recorded samples. Closing as out of scope.
