### ISSUE TITLE
"Regular Recorder" functions are not working in the example 

### ISSUE THREAD

**Issue by ebulanik** [fulldecent/FDSoundActivatedRecorder#35]
Hi there,

Thank you for this easy to use package.

Although "listening" & "playback" functions works perfect, I was not able get "Regular Recorder" functions working in the **example project**.

I also tried as stated in https://github.com/fulldecent/FDSoundActivatedRecorder/issues/31 but all it changed was -> started recording without trigger & stopped recording with same behaviour as listening.

So, I looked at the source code and realised that every timer interval there is a check which stops recording. 
`if let triggerLevel = triggerLevel, currentLevel <= triggerLevel {`
I think that is the line of code that needs an update, there can be a check here for regular recording use cases.

---------------------------
I introduced **regularRecording** to see a working example;
to start regular recorder ->
```
        recorder.regularRecording = true
        recorder.startListening()
        recorder.startRecording()
```

to stop recorder ->
```
        recorder.stopAndSaveRecording()
        recorder.regularRecording = false
```

initialize ->
```
class FDSoundActivatedRecorderMock: FDSoundActivatedRecorder {
    var intervalCallback: (Float)->() = {_ in}
    var regularRecording = false
    override func interval(currentLevel: Float) {
        self.intervalCallback(currentLevel)
        if regularRecording == false {
            super.interval(currentLevel: currentLevel)
        }
    }
    override init() {
        super.init()
    }
}
```

Best Regards,
Engin

**Comment by fulldecent** [comment]
This is okay for now. Please send as a PR.

In the future, this can be better documented on actually how `startRecording` is intended to work.

**Comment by ebulanik** [comment]
Figured out it is not an issue after all. The purpose of this code is to listen & record when there is some sound data.
